### ISSUE TITLE
amount issue for android version and response value issue

### ISSUE THREAD

**Issue by ibrahim-atif** [Magints-Technology-Solutions/payfort#1]
1) when using the plugin for android version the amount value has default value which is 1.00 not the real value which I send as a parameter in amount which is obvious in the first screen of pay fort.

2) the response of the method performPaymentRequest is nothing so in anonymous method then I do not have any values for the response so I cannot check the status code to be able to continue my own business.

thanks for your help.

![Screenshot_1627228151](https://user-images.githubusercontent.com/87941778/126905210-b07e42d0-59d5-4ee0-99c2-5d6f1d1f20cf.png)

**Comment by ItachiUchiha0** [comment]
Hello @ibrahim-atif,
We will fix it soon and inform you.
thanks

**Comment by ItachiUchiha0** [comment]
Hello @ibrahim-atif,
we published a  new release payfort_plugin: ^0.2.0+7
you can check it. 
Note:  the value object contains this data 
{amount=300, response_code=14000, card_number=400555******0001, card_holder_name=ahmed hamdy, payment_option=VISA, expiry_date=2501, customer_ip=197.62.252.127, eci=ECOMMERCE, language=en, fort_id=169996200002284586, command=PURCHASE, response_message=Success, sdk_token=b69c3ef3793249d685023fc4b38c7c4d, authorization_code=600278, merchant_reference=cbe05689-5531-4ded-aa1f-1c74a45efe6d, customer_email=uawe@gmail.com, token_name=b6a4722c0e044d4b8aa1f903ebf3c37a, currency=EGP, customer_name=ahmed, status=14}

let me know if everything is Ok.

**Comment by ibrahim-atif** [comment]
thanks a lot for your response
it runs well.
