### ISSUE TITLE
apple pay integration 

### ISSUE THREAD

**Issue by syrakozz** [Magints-Technology-Solutions/payfort#10]
i was able to integrate apple pay pay fort inside this plugin , 
plz check the code and it will be great if you can make an update for the plugin to support officialy payfort apple pay

import PassKit

if PKPaymentAuthorizationViewController.canMakePayments(usingNetworks: [.amex, .masterCard, .visa]) {
            let request = PKPaymentRequest.init()
            let payment = [PKPaymentSummaryItem(label: "Grand Total", amount: NSDecimalNumber(string:"20"))]
            request.paymentSummaryItems = payment
            request.countryCode = "US"
            request.currencyCode = "USD"
            
            //if let data = returnOrderDescription() {
             //   request.applicationData = data
          //  }
            request.supportedNetworks = [.amex, .masterCard, .visa, .discover]
            request.merchantIdentifier = "merchant.com.domain"
            request.merchantCapabilities = [.capability3DS ,.capabilityCredit , .capabilityDebit]

            let paymentPage = PKPaymentAuthorizationViewController(paymentRequest: request)
           paymentPage?.delegate = self
            if let paymentPage = paymentPage {
                controller!.present(paymentPage, animated: true, completion: nil)
            }
        }

   
    public func paymentAuthorizationViewControllerDidFinish(_ controller: PKPaymentAuthorizationViewController) {
        controller.dismiss(animated: true, completion: nil)
    }
    
    
    public func paymentAuthorizationViewController(_ controller: PKPaymentAuthorizationViewController, didAuthorizePayment payment: PKPayment, handler completion: @escaping (PKPaymentAuthorizationResult) -> Void) {
        
        if (payment.token.paymentData.count != 0) {
            // Call payfort
            let request: NSMutableDictionary = .init()
            
            self.payFort!.callPayFort(withRequest: request as! [String : String] ,
                                currentViewController: (UIApplication.shared.keyWindow?.rootViewController)!,
                                success: { (requestDic, responeDic) in
                                    print("success")
                completion(PKPaymentAuthorizationResult(status: .success, errors: nil))
                                   // result(responeDic)
            },
                                canceled: { (requestDic, responeDic) in
                                print("cancelled")

                completion(PKPaymentAuthorizationResult(status: .failure, errors: nil))
                                   // result(responeDic)
            },
                                faild: { (requestDic, responeDic, message) in
                                   print("failed "+message)
     
                                  //  result(message)
                completion(PKPaymentAuthorizationResult(status: .failure, errors: nil))
            })
        }else {
            completion(PKPaymentAuthorizationResult(status: .success, errors: nil))
           // completion(PKPaymentAuthorizationResult(status: .failure, errors: nil))
        }
    }

**Comment by ItachiUchiha0** [comment]
Hello @syrakozz 
OK, we Will try to add it in-shaa-allah.
Thanks

**Comment by mohammmedsedky** [comment]
Hello 
@ItachiUchiha0  
apple pay is added or not?

**Comment by mohammmedsedky** [comment]
@syrakozz  can you give me  steps for  apple pay config
