### ISSUE TITLE
amount value for android version

### ISSUE THREAD

**Issue by ibrahim-atif** [Magints-Technology-Solutions/payfort#2]
I hope you are fine.

Actually the amount value is divided by 100 as it is not the real value which I send to the method of the plugin.
I do not know why 
can I get your help please.

thanks.

**Comment by ItachiUchiha0** [comment]
Hello @ibrahim-atif,
 payfort working like that, if you enter 100 with SAR it means 100 by halala not SAR also 100 EGP means 100 piastres.
You can multiply by 100

**Comment by ibrahim-atif** [comment]
thanks for you response 
actually i have multiplied with 100 
but i wanted to make assure from what i did.

thank you again.
