### ISSUE TITLE
release version problem

### ISSUE THREAD

**Issue by ibrahim-atif** [Magints-Technology-Solutions/payfort#3]
I hope you are doing well.

Actually the debug version works very good.
but when trying to build release version the payfort plugin returns nothing.

So the payment operation fails.

Thanks A lot.

**Comment by ItachiUchiha0** [comment]
Hello @ibrahim-atif 
Are you generating a release SDK token from backend ?

**Comment by ibrahim-atif** [comment]
Hello @ItachiUchiha0 
I generate it using API
https://paymentservices.payfort.com/FortAPI/paymentApi

**Comment by ItachiUchiha0** [comment]
Please give me the response of this call and call params, also make sure you are running a release build.

**Comment by ibrahim-atif** [comment]
every  operation i did in debug mode runs so well.
but in release first i generate signature then use to to return the sdk token 
after that i use the token to call the method 
await PayfortPlugin.performPaymentRequest(
              'atmaTechNewOrder-${Configs.loginUser.user.phoneNumber}-${DateTime.now().year}${DateTime.now().month}${DateTime.now().day}${DateTime.now().hour}${DateTime.now().minute}${DateTime.now().second}',
              sdkTokenResponseModel.sdkToken,
              Configs.loginUser.user.fullName,
              language,
              Configs.loginUser.user.email ?? "info@atmatech.co",
              orderTotalCost,
              'PURCHASE',
              'SAR',
              '1' //zero for test mode and one for production
          ).then((value)
          {
            debugPrint('card number is ${value['card_number']}');
            print(value);
            returnedList.add(value['status']);
            returnedList.add(value['response_message']);
            returnedList.add(value['fort_id']);
          });

but the result is that card number is null 
and the payment pages not return at all just the previous result

**Comment by ItachiUchiha0** [comment]
Is sdkTokenResponseModel.sdkToken  returns release token ?

**Comment by ibrahim-atif** [comment]
I think i misunderstand you as  you  want the call parameters and response of sdk token itself 
so it is the method itself 
static Future<SdkTokenResponseVm> returnSDKToken(String deviceId) async
  {
    String signature = await getTokenSignature(deviceId);

    var bodyData = jsonEncode({
      'access_code': accessCode,
      'device_id': deviceId,
      'language': language,
      'merchant_identifier': merchantIdentifier,
      'service_command': "SDK_TOKEN",
      'signature': signature,
    });

    final response = await http.post(Uri.parse(paymentURL),
        body: bodyData,
        headers: {
          "Accept": "application/json",
          "content-type":"application/json"
        }
    );

    print("response.body");
    print(response.body);
    print("response.statusCode");
    print(response.statusCode);

    return SdkTokenResponseVm.fromJson(json.decode(response.body.toString()));
  }

the reponse is
 {"response_code":"22000","response_message":"عملية ناجحة","device_id":"d4b5c71a-a868-4f00-be28-02fc52d7268d","service_command":"SDK_T
OKEN","sdk_token":"07dd1b321c5b4854a03172c2b32672a5","signature":"48a9a17fb07f45154bde43b3f5c0d30633643fcfaf094c8ea559f99f8552c983","merchant_identifier
":"ZnvAmyNr","access_code":"OrFLjJVEq7vsxznSAT4U","language":"ar","status":"22"}

**Comment by ItachiUchiha0** [comment]
Ok, as per my knowledge there is some configuration from this call to tell payfort you need a release SDK token.

**Comment by ibrahim-atif** [comment]
buildTypes {
        release {
            //signingConfig signingConfigs.debug
            signingConfig signingConfigs.release
            shrinkResources false
            zipAlignEnabled false
            minifyEnabled false
        }

after some search i added this threecode  lines in build.gradle file
      shrinkResources false
      zipAlignEnabled false
      minifyEnabled false

the release version works well now .
I think the problem was code minifiction in release apk affects the payfort plugin negatively which cause it not working properly.
Thanks A lot for your response and interest i am so happy to get your help.

**Comment by ItachiUchiha0** [comment]
You are welcome any time, 
And already I asked you to check if you are running on release mode.
Good luck.
