### ISSUE TITLE
IOS Run 

### ISSUE THREAD

**Issue by ibrahim-atif** [Magints-Technology-Solutions/payfort#4]
i hope you are doing well
i have some bitty error which require your experience
in ios version run when i trigger payfort payment operation 
amazon initialization runs in infinite way without any payment screen.
so if there is any configuration for ios 
please do not hesitate to help me.
this is the error content 
2021-08-03 15:57:44.042143+0200 Runner[52112:500931] Task <4EC7C8AA-859B-423C-A140-1EAC9E318EF0>.<1> HTTP load failed, 0/0 bytes (error code: -999 [1:89])
2021-08-03 15:59:01.418214+0200 Runner[52112:501434] [] nw_connection_receive_internal_block_invoke [C3] Receive reply failed with error "Operation canceled"
2021-08-03 15:59:01.418417+0200 Runner[52112:501434] [] nw_connection_receive_internal_block_invoke [C3] Receive reply failed with error "Operation canceled"
2021-08-03 15:59:01.418876+0200 Runner[52112:501434] [] nw_connection_receive_internal_block_invoke [C3] Receive reply failed with error "Operation canceled"
2021-08-03 15:59:01.419095+0200 Runner[52112:501434] [] nw_connection_receive_internal_block_invoke [C3] Receive reply failed with error "Operation canceled"
![WhatsApp Image 2021-08-03 at 3 59 42 PM](https://user-images.githubusercontent.com/87941778/128028706-3628a045-e796-428d-aa63-6b1a017ae09e.jpeg)

thanks a lot

**Comment by ItachiUchiha0** [comment]
Hello @ibrahim-atif ,
Can you try running on a physical device ?

**Comment by ItachiUchiha0** [comment]
Hello @ibrahim-atif,
Any updates?

**Comment by ibrahim-atif** [comment]
Thanks for your interest.

Actually not yet.
As i have shifted to another task.
But i think at the middle of the next week i will complete my work and of
course communicate you to tell you if it works in physical device or no.

Thanks.

**Comment by ibrahim-atif** [comment]
I hope you are doing well.
unfortunately the same problem occurs on the physical device.
I have tested it but the same problem occurs.

**Comment by ItachiUchiha0** [comment]
hello @ibrahim-atif 
Sorry for being late.
We will fix it as soon as possible
thanks

**Comment by ibrahim-atif** [comment]
hi @ItachiUchiha0 

I hope you are fine
I wonder if you have any something new for this issue.
I hope to get good news from you.

Thanks.

**Comment by ItachiUchiha0** [comment]
Hello @ibrahim-atif,
I faced this issues also on native iOS  in version 3.0.1,
Already I'm Contacting payfort to Know what is the problem.
I sent them today and waiting for their reply.
I will contact you as soon as I found something
thank you.

**Comment by ibrahim-atif** [comment]
Hello @ItachiUchiha0 
There is anything new form payfort.
I hope to hear good news.

Thank You.

**Comment by ItachiUchiha0** [comment]
Hello @ibrahim-atif,
I'm really still contacting them and they can't help.
also I'm trying myself.
I Will contact you as soon as I got any result.
Thank you.

**Comment by ibrahim-atif** [comment]
Hello @ItachiUchiha0
I hope you are doing well.

There is anything new form payfort integration issue.
I hope to hear good news.
Thanks.

**Comment by ibrahim-atif** [comment]
Dear @ItachiUchiha0 
I hope you are doing well.

I have emailed payfort and told them about the problem.
Their response was to use the latest IOS SDK version.
The email which i have used is aluly@amazon.com
I hope to get your response.

![Capture24532453](https://user-images.githubusercontent.com/87941778/133435891-4a6a06eb-bf59-42a1-9f04-b06d08dc5048.PNG)

**Comment by syrakozz** [comment]
the problem is in swift code of the plugin you need to initial the controller before entering the class , 

   var navigationController: UINavigationController?
    var payFort = PayFortController.init(enviroment: .sandBox) // put this line after the navigation and commen out the payfort controll initialise inside the function 

@ItachiUchiha0 can you plz update the plugin

**Comment by ItachiUchiha0** [comment]
@syrakozz thank you for your help, please check now

**Comment by syrakozz** [comment]
the version of this library in github is still old 2.0.6 but the version in dart flutter 3.1 plz check
