### ISSUE TITLE
can't run on IOS

### ISSUE THREAD

**Issue by ahmedashraf344** [Magints-Technology-Solutions/payfort#5]
<img width="1533" alt="Screen Shot 2021-08-26 at 1 38 00 PM" src="https://user-images.githubusercontent.com/44755718/130956310-c5dc3abc-7923-49c9-80f1-e483f71b35b7.png">

**Comment by ItachiUchiha0** [comment]
Hello @ahmedashraf344,
go to project folder and run this command in terminal 
flutter clean && flutter pub get && cd ios && pod install
thanks

**Comment by ItachiUchiha0** [comment]
Hello, please check now
thank you
